### ISSUE TITLE
Weekly build status (1)

### ISSUE THREAD

**Issue by krasCGQ** [krasCGQ/aarch64-linux-android#1]
No update will be made for this week. Once server is migrated to another one, I'll execute a build ASAP.

Issue will be closed once this is done.

**Comment by RiteshSaxena** [comment]
please also update the a53 tc after your sever migration is done. Thank you.

**Comment by krasCGQ** [comment]
Maybe I'll be doing 2 builds: GNU one weekly and Linaro one which will be depending on how often Linaro pushes changes. Both will be generic toolchain.

The only difference between so-called A53 toolchain and generic one is that A53 toolchain passes `-mcpu=cortex-a53` by default, limiting support only to chipsets with (only) Cortex-A53 CPU(s), which actually can be passed by defining it manually to kernel's Makefile like KudProject/kernel_xiaomi_msm8953@821348e4a87c.

The generic toolchain I configured to pass `-march=armv8-a+crc+crypto` by default so it should be compatible with all ARMv8-A CPUs.

**Comment by RiteshSaxena** [comment]
i already have that commit in my kernel. i didn't knew its just that. Thanks anyway.
